version: '3.7'
services:
  greetings-aot:
    image: "lutrh/greeting-aot"
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 200M
  greetings-jit:
    image: "lutrh/greeting-jit"
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 200M